export const Bosses = [
  '"Statue of Marble and Brass"',
  'Aeonblight Drake',
  'Algorithm of Semi-Intransient Matrix of Overseer Network',
  'All-Devouring Narwhal',
  'Andrius',
  'Anemo Hypostasis',
  'Azhdaha',
  'Childe',
  'Coral Defenders',
  'Cryo Hypostasis',
  'Cryo Regisvine',
  'Dendro Hypostasis',
  'Electro Hypostasis',
  'Electro Regisvine',
  'Emperor of Fire and Iron',
  'Everlasting Lord of Arcane Wisdom',
  'Geo Hypostasis',
  'Golden Wolflord',
  "Guardian of Apep's Oasis",
  'Hydro Hypostasis',
  'Hydro Tulpa',
  'Icewind Suite',
  'Iniquitous Baptist',
  'Jadeplume Terrorshroom',
  'La Signora',
  'Magatsu Mitake Narukami no Mikoto',
  'Maguu Kenki',
  'Millennial Pearl Seahorse',
  'Perpetual Mechanical Array',
  'Primo Geovishap',
  'Prototype Cal. Breguet',
  'Pyro Hypostasis',
  'Pyro Regisvine',
  'Rhodeia of Loch',
  'Ruin Serpent',
  'Setekh Wenut',
  'Solitary Suanni',
  'Stormterror Dvalin',
  'The Knave',
  'Thunder Manifestation',
] as const;
